### ISSUE TITLE
crash when clicking [cancel] in sfod 

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#350]
vst2 running in carla --gdb

after clicking cancel

```
Thread 1 "carla" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Bestand of map bestaat niet.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7dd9859 in __GI_abort () at abort.c:79
#2  0x00007ffff7e443ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7f6e285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7e4c47c in malloc_printerr (str=str@entry=0x7ffff7f701e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
#4  0x00007ffff7e4c6cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
#5  0x00007fffbd83bceb in DISTRHO::FileBrowserData::~FileBrowserData() (this=0x7fffe8007af0, __in_chrg=<optimized out>) at ../DPF/distrho/src/../extra/FileBrowserDialog.cpp:242
#6  0x00007fffbd8b0f0c in DISTRHO::fileBrowserClose(DISTRHO::FileBrowserData*) (handle=0x7fffe8007af0) at ../DPF/dgl/src/../../distrho/extra/FileBrowserDialog.cpp:571
#7  0x00007fffbd85fe05 in DGL::Window::PrivateData::idleCallback() (this=0x2280480) at ../DPF/dgl/src/WindowPrivateData.cpp:406
#8  0x00007fffbd8471d6 in DGL::Application::PrivateData::triggerIdleCallbacks() (this=0x221a300) at ../DPF/dgl/src/ApplicationPrivateData.cpp:129
#9  0x00007fffbd84714a in DGL::Application::PrivateData::idle(unsigned int) (this=0x221a300, timeoutInMs=0) at ../DPF/dgl/src/ApplicationPrivateData.cpp:121
#10 0x00007fffbd84625d in DGL::Application::idle() (this=0x7fffe80087b0) at ../DPF/dgl/src/Application.cpp:33
#11 0x00007fffbd829a13 in DISTRHO::UIExporter::plugin_idle() (this=0x2498ca0) at ../DPF/distrho/src/DistrhoUIInternal.hpp:245
#12 0x00007fffbd82a001 in DISTRHO::UIVst::idle() (this=0x2498c80) at ../DPF/distrho/src/DistrhoPluginVST2.cpp:220
#13 0x00007fffbd82b440 in DISTRHO::PluginVst::vst_dispatcher(int, int, long, void*, float) (this=0x1ce6aa0, opcode=19, index=0, value=0, ptr=0x0, opt=0) at ../DPF/distrho/src/DistrhoPluginVST2.cpp:773
#14 0x00007fffbd825818 in DISTRHO::vst_dispatcherCallback(AEffect*, int32_t, int32_t, intptr_t, void*, float) (effect=0x1d3b600, opcode=19, index=0, value=0, ptr=0x0, opt=0) at ../DPF/distrho/src/DistrhoPluginVST2.cpp:1617
#15 0x00007fffec70facf in  () at /usr/lib/carla/libcarla_standalone2.so
#16 0x00007fffec6430b9 in CarlaBackend::CarlaEngine::idle() () at /usr/lib/carla/libcarla_standalone2.so
#17 0x00007fffec68a68a in  () at /usr/lib/carla/libcarla_standalone2.so
#18 0x00007fffec629d4c in carla_engine_idle () at /usr/lib/carla/libcarla_standalone2.so
#19 0x00007ffff73deff5 in  () at /lib/x86_64-linux-gnu/libffi.so.7
#20 0x00007ffff73de40a in  () at /lib/x86_64-linux-gnu/libffi.so.7
#21 0x00007ffff7525316 in _ctypes_callproc () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#22 0x00007ffff7525af7 in  () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#23 0x00000000005f6a46 in _PyObject_MakeTpCall ()
#24 0x0000000000570a1f in _PyEval_EvalFrameDefault ()
#25 0x000000000050ac5e in  ()
#26 0x00000000005703e6 in _PyEval_EvalFrameDefault ()
#27 0x000000000050ac5e in  ()
#28 0x00000000005703e6 in _PyEval_EvalFrameDefault ()
#29 0x00000000005f6226 in _PyFunction_Vectorcall ()
#30 0x000000000050ad5c in  ()
--Type <RET> for more, q to quit, c to continue without paging--
#31 0x00000000005f55f2 in PyObject_Call ()
#32 0x00007ffff729942c in  () at /usr/lib/python3/dist-packages/sip.cpython-38-x86_64-linux-gnu.so
#33 0x00007ffff7299513 in  () at /usr/lib/python3/dist-packages/sip.cpython-38-x86_64-linux-gnu.so
#34 0x00007ffff2d496a1 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#35 0x00007ffff2e3a380 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#36 0x00007ffff6a71cf5 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007ffff26f825d in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff280d148 in QMainWindow::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007ffff2e5919b in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#40 0x00007ffff26b5a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007ffff26bf0f0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#42 0x00007ffff2fbcbf6 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#43 0x00007ffff6a4593a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007ffff6a9c8b0 in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007ffff6a9d19c in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007ffff6e2a17d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007ffff6e2a400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff6e2a4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff6a9d565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007ffff6a444db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007ffff6a4c246 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007ffff2f7d9c1 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so
#53 0x00000000005f5f1a in PyCFunction_Call ()
#54 0x00000000005f6a46 in _PyObject_MakeTpCall ()
#55 0x0000000000570a1f in _PyEval_EvalFrameDefault ()
#56 0x00000000005f6226 in _PyFunction_Vectorcall ()
#57 0x000000000056b5e0 in _PyEval_EvalFrameDefault ()
#58 0x00000000005696da in _PyEval_EvalCodeWithName ()
#59 0x000000000068db17 in PyEval_EvalCode ()
#60 0x000000000067eeb1 in  ()
#61 0x000000000067ef2f in  ()
--Type <RET> for more, q to quit, c to continue without paging--
#62 0x000000000067efd1 in  ()
#63 0x000000000067f377 in PyRun_SimpleFileExFlags ()
#64 0x00000000006b7902 in Py_RunMain ()
#65 0x00000000006b7c8d in Py_BytesMain ()
#66 0x00007ffff7ddb0b3 in __libc_start_main (main=0x4eed30 <main>, argc=5, argv=0x7fffffffdf98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf88) at ../csu/libc-start.c:308
#67 0x00000000005fb12e in _start ()

```

**Comment by falkTX** [comment]
Fixed in develop
