### ISSUE TITLE
[develop] crash when canceling file dialog ; munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/DPF#358]
```
Core was generated by `/home/rob/git/ClearlyBroken/ninjas2/build/bin/ninjas2'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Bestand of map bestaat niet.
[Current thread is 1 (Thread 0x7f44d53aa740 (LWP 60507))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f44d5844859 in __GI_abort () at abort.c:79
#2  0x00007f44d58af3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f44d59d9285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f44d58b747c in malloc_printerr (str=str@entry=0x7f44d59db1e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
#4  0x00007f44d58b76cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
#5  0x000055d34a4b9d6d in DISTRHO::FileBrowserData::~FileBrowserData (this=0x55d34c4ff970, __in_chrg=<optimized out>) at ../dpf/distrho/src/../extra/FileBrowserDialog.cpp:242
#6  0x000055d34a569988 in DISTRHO::fileBrowserClose (handle=0x55d34c4ff970) at ../dpf/dgl/src/../../distrho/extra/FileBrowserDialog.cpp:571
#7  0x000055d34a518821 in DGL::Window::PrivateData::idleCallback (this=0x55d34b5a4ba0) at ../dpf/dgl/src/WindowPrivateData.cpp:410
#8  0x000055d34a4fec0c in DGL::Application::PrivateData::triggerIdleCallbacks (this=0x55d34b58ac00) at ../dpf/dgl/src/ApplicationPrivateData.cpp:129
#9  0x000055d34a4feb80 in DGL::Application::PrivateData::idle (this=0x55d34b58ac00, timeoutInMs=30) at ../dpf/dgl/src/ApplicationPrivateData.cpp:121
#10 0x000055d34a4fdd0d in DGL::Application::exec (this=0x55d34b58ab60, idleTimeInMs=30) at ../dpf/dgl/src/Application.cpp:41
#11 0x000055d34a4a7d6e in DISTRHO::UIExporter::exec (this=0x7ffffa38d3b0, cb=0x7ffffa38d390) at ../dpf/distrho/src/DistrhoUIInternal.hpp:226
#12 0x000055d34a4a9647 in DISTRHO::PluginJack::PluginJack (this=0x7ffffa38d390, client=0x55d34b585b20) at ../dpf/distrho/src/DistrhoPluginJACK.cpp:223
#13 0x000055d34a4a4c9b in main (argc=1, argv=0x7ffffa38e528) at ../dpf/distrho/src/DistrhoPluginJACK.cpp:982
(gdb) 
```

**Comment by falkTX** [comment]
dpf is updated to the very latest, correct?

**Comment by rghvdberg** [comment]
correct,
last commit 
```
commit 7f206b99dcccadbf26376ea6db0b9557800dd97d (HEAD -> develop, origin/develop)
Author: falkTX <falktx@falktx.com>
Date:   Fri Jan 7 18:02:56 2022 +0000

    Fix previous commit, upstream is slightly borked
    
    Signed-off-by: falkTX <falktx@falktx.com>
 ```
